### ISSUE TITLE
More than 6 Images

### ISSUE THREAD

**Issue by CattoGamer** [LordNature/Simplexity#2]
First of all I want tell you that I like you Loadingscreen.
but their is a small restriction in this,to the sideshow can only be added 6 images

Because I Wanted to create a slideshow with wallpapers of MLP and all their Elements.

Also,how do I make it that for every Image a unique Text on the bottom right?

**Comment by LordNature** [comment]
@FarukGamer The limitation on the images can easily be fixed if you want me to fix it. I also can do the text, probably. Currently busy, so I can't do much at the moment. I'll work on it in approximately... 15 days? I will also add more designs, maybe.

**Comment by CattoGamer** [comment]
I will come back soon to this issue
